name: Auto Commit

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update activity file
        run: |
          echo "Last updated: $(date -u)" > activity.md

      - name: Commit changes
        run: |
          git config user.name "fahiza-djamil"
          git config user.email "fahizadjamil@gmail.com"
          git add activity.md
          git commit -m "Auto update: $(date -u)" || echo "Nothing to commit"
          git push origin HEAD
